# Generated by Django 5.2.6 on 2025-11-19 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='市区町村名')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県名')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='境界線データ')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='人口')),
                ('empty_house_rate', models.FloatField(blank=True, null=True, verbose_name='空き家率')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='navi.region')),
            ],
            options={
                'unique_together': {('region', 'year')},
            },
        ),
    ]
